#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SMAMobile.Droid.Resource", IsApplication=true)]

namespace SMAMobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int collections_view_as_list = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_accept = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_discard = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_go_to_today = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_import_export = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_merge = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_mic = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_new = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_play_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_refresh = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_save = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_search = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_stop = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_stop_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_time = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_video_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Service_Market = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int SMA128 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Splash = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MyButton = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int DashboardActivityActions = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int anunciosSyncError = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
