//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_AnunciosExtras
    {
        public int AE_Id { get; set; }
        public int AN_Id { get; set; }
        public string AN_Nombre { get; set; }
        public string AN_ImagenUrl { get; set; }
    
        public virtual AN_Anuncios AN_Anuncios { get; set; }
    }
}
