//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_Compañia
    {
        public int COM_Id { get; set; }
        public string COM_Nombre { get; set; }
        public string COM_Direccion { get; set; }
        public string COM_Telefono { get; set; }
        public string COM_Correo { get; set; }
        public string COM_Web { get; set; }
        public string COM_ContactoNombre { get; set; }
        public string COM_ContactoCelular { get; set; }
        public string COM_ContactoEmail { get; set; }
        public byte[] COM_Logo { get; set; }
    }
}
