//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CON_Contactenos
    {
        public int CON_Id { get; set; }
        public string CON_Nombre { get; set; }
        public string CON_Telefono { get; set; }
        public string CON_Celular { get; set; }
        public string CON_Email { get; set; }
        public string CON_Mensaje { get; set; }
        public System.DateTime CON_Fecha { get; set; }
    }
}
