//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_Parametros
    {
        public int CONG_Id { get; set; }
        public Nullable<int> CONF_QtyAnuncios { get; set; }
        public Nullable<int> CONF_DayBlocked { get; set; }
        public Nullable<int> CONF_Comments { get; set; }
        public Nullable<int> CONF_Alerts { get; set; }
        public Nullable<int> CONF_InactivityDay { get; set; }
        public Nullable<int> CONF_DayEnabled { get; set; }
    }
}
