//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_ComentarioReview
    {
        public int CR_Id { get; set; }
        public int UserIdContratado { get; set; }
        public int UserIdSolicitante { get; set; }
        public int SS_Id { get; set; }
        public string CR_Comentario { get; set; }
        public int ST_Id { get; set; }
    
        public virtual SS_SolicitudServicio SS_SolicitudServicio { get; set; }
        public virtual ST_Estatus ST_Estatus { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
