//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQs
    {
        public int FAQ_Id { get; set; }
        public string FAQ_Question { get; set; }
        public string FAQ_Answer { get; set; }
        public int FAQ_Status { get; set; }
    
        public virtual ST_Estatus ST_Estatus { get; set; }
    }
}
