//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_MultimediaTipos
    {
        public MT_MultimediaTipos()
        {
            this.AM_MultimediaAnuncios = new HashSet<AM_MultimediaAnuncios>();
        }
    
        public int MT_Id { get; set; }
        public string MT_Descripcion { get; set; }
    
        public virtual ICollection<AM_MultimediaAnuncios> AM_MultimediaAnuncios { get; set; }
    }
}
