//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_Paises
    {
        public PA_Paises()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int PA_Id { get; set; }
        public string PA_Descripcion { get; set; }
        public int REG_Id { get; set; }
    
        public virtual REG_Region REG_Region { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
