//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_Paises
    {
        public PA_Paises()
        {
            this.UserProfile = new HashSet<UserProfile>();
            this.AN_Anuncios = new HashSet<AN_Anuncios>();
        }
    
        public int PA_Id { get; set; }
        public string PA_Descripcion { get; set; }
        public int PA_ISONUM { get; set; }
        public string PA_ISO2 { get; set; }
        public string PA_ISO3 { get; set; }
    
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual ICollection<AN_Anuncios> AN_Anuncios { get; set; }
    }
}
