//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_Region
    {
        public REG_Region()
        {
            this.PA_Paises = new HashSet<PA_Paises>();
        }
    
        public int REG_Id { get; set; }
        public string REG_Descripcion { get; set; }
    
        public virtual ICollection<PA_Paises> PA_Paises { get; set; }
    }
}
