//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RT_TipoReview
    {
        public RT_TipoReview()
        {
            this.RW_Reviews = new HashSet<RW_Reviews>();
        }
    
        public int RT_Id { get; set; }
        public string RT_Descripcion { get; set; }
    
        public virtual ICollection<RW_Reviews> RW_Reviews { get; set; }
    }
}
