//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RW_Reviews
    {
        public RW_Reviews()
        {
            this.CR_ComentarioReview = new HashSet<CR_ComentarioReview>();
        }
    
        public int RW_Id { get; set; }
        public int SS_Id { get; set; }
        public string RW_Comentario { get; set; }
        public System.DateTime RW_Fecha { get; set; }
        public Nullable<byte> RW_Rate { get; set; }
        public Nullable<int> ST_Id { get; set; }
    
        public virtual SS_SolicitudServicio SS_SolicitudServicio { get; set; }
        public virtual ST_Estatus ST_Estatus { get; set; }
        public virtual ICollection<CR_ComentarioReview> CR_ComentarioReview { get; set; }
    }
}
