//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_SubCategoriaServicio
    {
        public SBS_SubCategoriaServicio()
        {
            this.AN_Anuncios = new HashSet<AN_Anuncios>();
        }
    
        public int SBS_Id { get; set; }
        public Nullable<int> CD_Id { get; set; }
        public string SBS_Descripcion { get; set; }
    
        public virtual CD_CategoriaServicio CD_CategoriaServicio { get; set; }
        public virtual ICollection<AN_Anuncios> AN_Anuncios { get; set; }
    }
}
