//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.AN_Anuncios = new HashSet<AN_Anuncios>();
            this.CR_ComentarioReview = new HashSet<CR_ComentarioReview>();
            this.CR_ComentarioReview1 = new HashSet<CR_ComentarioReview>();
            this.SS_SolicitudServicio = new HashSet<SS_SolicitudServicio>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> PA_Id { get; set; }
        public byte[] Image { get; set; }
        public int MP_MemberShipId { get; set; }
        public int ST_Id { get; set; }
    
        public virtual ICollection<AN_Anuncios> AN_Anuncios { get; set; }
        public virtual ICollection<CR_ComentarioReview> CR_ComentarioReview { get; set; }
        public virtual ICollection<CR_ComentarioReview> CR_ComentarioReview1 { get; set; }
        public virtual MB_Membresia MB_Membresia { get; set; }
        public virtual PA_Paises PA_Paises { get; set; }
        public virtual ICollection<SS_SolicitudServicio> SS_SolicitudServicio { get; set; }
        public virtual ST_Estatus ST_Estatus { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
